// Command provision_sql prints the SQL that sets this gateway up to pay people.
//
//	PAYMENT_CREDENTIALS_MASTER_KEY_B64=… go run ./cmd/provision_sql > seed.sql
//	psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f seed.sql
//
// WHY THIS EXISTS RATHER THAN A PLAIN .sql FILE. Everything here could be
// written by hand except one column. A payout destination is stored as
// AES-256-GCM ciphertext under PAYMENT_CREDENTIALS_MASTER_KEY_B64, and the
// encryption is bound to the row's own UUID:
//
//	{"version":1,"nonce":"…","ciphertext":"…"}   AAD = id:recipient_id:provider:version
//
// No SQL produces that, and pgcrypto has no GCM. So this generates the UUIDs
// first, encrypts against them with the gateway's own cipher — the same code
// path the API uses, so the format cannot drift — and prints the result as
// ordinary INSERT statements you can read before running.
//
// It touches no database. It prints SQL and exits.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/google/uuid"

	"example.com/fiber-mvc/internal/credentials"
	"example.com/fiber-mvc/internal/storage"
)

// payee is one property and where its money lands.
type payee struct {
	Name      string
	Reference string
	DKPG      map[string]string
	Stripe    map[string]string
}

var payees = []payee{
	{
		Name:      "Lhaki Hotels",
		Reference: "merchant-lhaki-hotels",
		DKPG: map[string]string{
			"beneficiary_account": "110158212197",
			"beneficiary_name":    "PG_AVS",
			"beneficiary_bank":    "1060",
		},
		Stripe: map[string]string{
			"submerchant_id": "2504188100000003",
			"dk_account":     "8288821831",
		},
	},
	{
		Name:      "Dash Hotels",
		Reference: "merchant-dash-hotels",
		DKPG: map[string]string{
			"beneficiary_account": "110102183048",
			"beneficiary_name":    "Niraj Bhattarai",
			"beneficiary_bank":    "1060",
		},
		Stripe: map[string]string{
			"submerchant_id": "MERCHANT_001",
			"dk_account":     "110102183048",
		},
	},
}

// quote renders a SQL string literal. Everything here is operator-supplied
// configuration rather than user input, but a name with an apostrophe in it
// would otherwise produce a file that will not parse.
func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

func main() {
	appID := flag.String("app-id", "", "the integration app these mappings belong to, e.g. APP-1komYw")
	flag.Parse()

	if strings.TrimSpace(*appID) == "" {
		fmt.Fprintln(os.Stderr, "--app-id is required: routing is keyed on (app, merchant_reference)")
		os.Exit(2)
	}

	cipher, err := credentials.NewFromBase64(os.Getenv("PAYMENT_CREDENTIALS_MASTER_KEY_B64"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "PAYMENT_CREDENTIALS_MASTER_KEY_B64: %v\n\n"+
			"Run this where the gateway's own environment is, or the destinations\n"+
			"it writes cannot be decrypted by the gateway that has to use them.\n", err)
		os.Exit(1)
	}

	out := os.Stdout
	fmt.Fprintf(out, `-- Generated by cmd/provision_sql. Safe to run twice.
--
-- The encrypted_credentials values below are bound to the UUIDs in this file.
-- Regenerating produces different UUIDs and different ciphertext; both are
-- valid, but do not mix statements from two runs.

\set ON_ERROR_STOP on
BEGIN;

`)

	for _, p := range payees {
		recipientID := uuid.NewString()

		fmt.Fprintf(out, "-- %s\n", p.Name)
		fmt.Fprintf(out, `INSERT INTO payment_recipients (id, name, is_active, created_at, updated_at)
SELECT '%s', %s, true, now(), now()
WHERE NOT EXISTS (SELECT 1 FROM payment_recipients WHERE name = %s);

`, recipientID, quote(p.Name), quote(p.Name))

		for _, spec := range []struct {
			provider string
			values   map[string]string
		}{{"dkpg", p.DKPG}, {"stripe", p.Stripe}} {
			credentialID := uuid.NewString()
			plaintext, err := json.Marshal(spec.values)
			if err != nil {
				fmt.Fprintf(os.Stderr, "encode %s credentials for %s: %v\n", spec.provider, p.Name, err)
				os.Exit(1)
			}
			// The AAD ties this ciphertext to this row. Move it to another row
			// and it stops decrypting, which is the point: a destination cannot
			// be copied onto a different payee.
			aad := storage.CredentialAdditionalData(credentialID, recipientID, spec.provider, 1)
			sealed, err := cipher.Encrypt(plaintext, aad)
			if err != nil {
				fmt.Fprintf(os.Stderr, "encrypt %s credentials for %s: %v\n", spec.provider, p.Name, err)
				os.Exit(1)
			}

			// Inserted active. The API creates drafts so a half-typed account
			// cannot take money before somebody checks it; here the values are
			// in the file above, reviewed before it is run.
			fmt.Fprintf(out, `INSERT INTO gateway_credential_configurations (
    id, recipient_id, provider, version, status, encrypted_credentials,
    encryption_key_id, created_at, updated_at, activated_at, created_by, updated_by)
SELECT '%s', r.id, '%s', 1, 'active', %s,
    'env:PAYMENT_CREDENTIALS_MASTER_KEY_B64', now(), now(), now(), 'provision_sql', 'provision_sql'
FROM payment_recipients r
WHERE r.name = %s
  AND NOT EXISTS (
      SELECT 1 FROM gateway_credential_configurations c
      WHERE c.recipient_id = r.id AND c.provider = '%s' AND c.status = 'active');

`, credentialID, spec.provider, quote(sealed), quote(p.Name), spec.provider)
		}

		fmt.Fprintf(out, `INSERT INTO integration_recipient_mappings (
    id, external_app_id, external_merchant_reference, recipient_id, is_active, created_at, updated_at)
SELECT '%s', %s, %s, r.id, true, now(), now()
FROM payment_recipients r
WHERE r.name = %s
  AND NOT EXISTS (
      SELECT 1 FROM integration_recipient_mappings
      WHERE external_app_id = %s AND external_merchant_reference = %s);

`, uuid.NewString(), quote(*appID), quote(p.Reference), quote(p.Name), quote(*appID), quote(p.Reference))
	}

	fmt.Fprint(out, `COMMIT;

\echo ''
\echo 'Who can now be paid:'
SELECT r.name AS payee,
       m.external_merchant_reference AS merchant_reference,
       string_agg(c.provider, ', ' ORDER BY c.provider) AS destinations
FROM payment_recipients r
JOIN integration_recipient_mappings m ON m.recipient_id = r.id AND m.is_active
JOIN gateway_credential_configurations c ON c.recipient_id = r.id AND c.status = 'active'
WHERE r.is_active
GROUP BY r.name, m.external_merchant_reference
ORDER BY r.name;
`)
}
